### ISSUE TITLE
Unsupported TrueNAS Scale version 24.10.1

### ISSUE THREAD

**Issue by sonynut** [0x556c79/install_ugreen_leds_controller#1]
Tried running and got the below error:
Unsupported TreNAS SACALE version: 24.10.1.
Please build the kernel module manually.

**Comment by 0x556c79** [comment]
There is no kernel module for version 24.10.1 in the repository of [miskcoo](https://github.com/miskcoo/ugreen_leds_controller) who developed the whole thing.
I just tried to build the kernel module for the version 24.10.1 myself but it fails because there is no Packages.gz file yet. This is needed to create the truenas build environment.

```
+ wget https://download.truenas.com/TrueNAS-SCALE-ElectricEel/24.10.1/packages/Packages.gz
--2024-12-22 00:39:59--  https://download.truenas.com/TrueNAS-SCALE-ElectricEel/24.10.1/packages/Packages.gz
Resolving download.truenas.com (download.truenas.com)... 185.244.226.2, 64:ff9b::b9f4:e202
Connecting to download.truenas.com (download.truenas.com)|185.244.226.2|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-12-22 00:40:00 ERROR 404: Not Found.
```

miskcoo has a github action that tries to build the kernel modules every day, when it is available it should be here. I have adapted the script so that the supported version is now obtained directly from the repository. If the kernel module appears there, it is automatically recognized without having to adapt the variable in the script.

https://github.com/miskcoo/ugreen_leds_controller/tree/gh-actions/build-scripts/truenas/build/TrueNAS-SCALE-ElectricEel

**Comment by iboutsikas** [comment]
Any ideas on how long it takes for the packages.gz archive to be published? I has been a hot minute since 24.10.1 went out

**Comment by pxlidxn** [comment]
> Any ideas on how long it takes for the packages.gz archive to be published? I has been a hot minute since 24.10.1 went out

As long as it takes since this is voluntary and the person who created it may actually have a life?

**Comment by 0x556c79** [comment]
> Any ideas on how long it takes for the packages.gz archive to be published? I has been a hot minute since 24.10.1 went out

No, I have no idea.
That depends on iXsystems who are developing TrueNAS. I don't know who and when this will be provided.
Maybe it was just forgotten.
You could ask iXsystems directly or ask in the TrueNAS forum.

**Comment by iboutsikas** [comment]
> > Any ideas on how long it takes for the packages.gz archive to be published? I has been a hot minute since 24.10.1 went out
> 
> No, I have no idea. That depends on iXsystems who are developing TrueNAS. I don't know who and when this will be provided. Maybe it was just forgotten. You could ask iXsystems directly or ask in the TrueNAS forum.

I am aware, was just wondering if this had happened before. I will be asking and let you know if I get anything back.

**Comment by iboutsikas** [comment]
I've been doing some digging since there does not seem to be any replies from iXSystems. The reason the misckoo's repo needs packages is to extract which linux headers to use. Turns out, 24.10.1 and 24.10.0.2 are both using `6.6.44-production+truenas` as their kernel so the headers will be the same. 

I created a [PR](https://github.com/0x556c79/install_ugreen_leds_controller/pull/2) to add options to handle this use case for your script. I've been running with the 24.10.0.2 module for a few hours now and it seems to be working. Let me know if you need any changes/additions.

**Comment by 0x556c79** [comment]
> I've been doing some digging since there does not seem to be any replies from iXSystems. The reason the misckoo's repo needs packages is to extract which linux headers to use. Turns out, 24.10.1 and 24.10.0.2 are both using `6.6.44-production+truenas` as their kernel so the headers will be the same.
> 
> I created a [PR](https://github.com/0x556c79/install_ugreen_leds_controller/pull/2) to add options to handle this use case for your script. I've been running with the 24.10.0.2 module for a few hours now and it seems to be working. Let me know if you need any changes/additions.

Thank you, PR is merged.
